{"name": "test_text_messages[union_id-positive_基础文本消息测试0]", "status": "failed", "statusDetails": {"message": "AssertionError: 状态码不匹配，期望 200，实际 429", "trace": "tests/api/message/test_message.py:59: in test_text_messages\n    _generic_message_test(feishu_client, prepared_test_case, receiver_info)\ntests/api/message/test_message.py:116: in _generic_message_test\n    ResponseValidator.validate_status_code(response, expected[\"status_code\"])\ntests/utils/response_validator.py:13: in validate_status_code\n    assert actual_code == expected_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   AssertionError: 状态码不匹配，期望 200，实际 429"}, "steps": [{"name": "Step 1: 准备测试用例", "status": "passed", "start": 1752043016943, "stop": 1752043016943}, {"name": "Step 2: 发送请求", "status": "passed", "start": 1752043016944, "stop": 1752043017167}, {"name": "Step 3: 验证响应", "status": "failed", "statusDetails": {"message": "AssertionError: 状态码不匹配，期望 200，实际 429\n", "trace": "  File \"/Users/taoj/Desktop/FeishuAPITestnew-main/tests/api/message/test_message.py\", line 116, in _generic_message_test\n    ResponseValidator.validate_status_code(response, expected[\"status_code\"])\n  File \"/Users/taoj/Desktop/FeishuAPITestnew-main/tests/utils/response_validator.py\", line 13, in validate_status_code\n    assert actual_code == expected_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1752043017167, "stop": 1752043017167}], "parameters": [{"name": "receiver_info", "value": "('union_id', 'ou_d02a396023f166c2ba8a36b92184f5ba:')"}, {"name": "prepared_test_case", "value": "<tests.test_data.case_loader.TestCase object at 0x1064bf560>"}], "start": 1752043016943, "stop": 1752043017168, "uuid": "72fc7aaf-669d-4905-aa07-2e65373ff7ea", "testCaseId": "e3ec8bf0877ed7ded8aa02fb6cf06e8d", "fullName": "tests.api.message.test_message#test_text_messages"}